# * @author Michal Krombholz
# * @license Creative Commons Attribution-ShareAlike 3.0 (CC BY-SA 3.0)
# * http://creativecommons.org/licenses/by-sa/3.0/
# *
# * Works may contain parts by others and are licencsed by their corresponding, original licenses.

# put your *.o targets here, make should handle the rest!
SRCS += main.c irRcvInput.c
SRCS += irRcv.c

# define here or uncomment the #define in irRcv.h
#CFLAGS += -DIR_SYMA
#CFLAGS += -DIR_TRACERJET
#CFLAGS += -DIR_USERIES


# common make definition
include ../../lib/common.mk
